import type { Metadata } from "next";
import ToolLayout from "@/components/ToolLayout";
import SudokuClient from "./SudokuClient";

export const metadata: Metadata = {
  title: "Sudoku - Play Free Online Sudoku Puzzles | MultiTool",
  description:
    "Play free Sudoku online with 4 difficulty levels, pencil notes, hints, undo and timer. Every puzzle is generated fresh with a single guaranteed solution — in your browser.",
  keywords: [
    "sudoku",
    "sudoku online",
    "play sudoku free",
    "sudoku puzzle",
    "sudoku easy",
    "sudoku medium",
    "sudoku hard",
    "sudoku expert",
    "web sudoku",
  ],
  alternates: {
    canonical: "https://www.multitoolbox.online/tools/games/sudoku",
  },
  openGraph: {
    title: "Sudoku - Play Free Online Sudoku Puzzles | MultiTool",
    description:
      "Free Sudoku with 4 difficulty levels, notes and hints. Every puzzle has a single solution.",
    url: "https://www.multitoolbox.online/tools/games/sudoku",
    siteName: "MultiTool",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Sudoku - Free Online Sudoku Puzzles",
    description: "4 difficulty levels, notes, hints and timer — plays in your browser.",
  },
};

export default function SudokuPage() {
  return (
    <ToolLayout
      title="Sudoku"
      description="The classic number puzzle with a modern twist. Four difficulty levels, pencil notes, hints, undo and a timer — every game is a fresh puzzle with exactly one solution."
      categoryName="Games"
      categorySlug="games"
      toolSlug="sudoku"
      howItWorks={
        <>
          <h2 className="font-display text-xl font-semibold mb-3">
            How to play Sudoku
          </h2>
          <p className="mb-4">
            The board is a 9×9 grid divided into nine 3×3 boxes. Some cells
            come pre-filled with digits — these are your clues and cannot be
            changed. Your job: fill every empty cell so that{" "}
            <strong>each row, each column and each 3×3 box contains the
            digits 1 to 9 exactly once</strong>.
          </p>
          <p className="mb-4">
            Three rules of thumb that solve most easy puzzles: start with the
            row, column or box that has the most digits; look for cells where
            only one digit can legally fit; and use pencil notes (✏) to keep
            track of candidates. When you place a digit, the notes in the
            same row, column and box are cleaned up automatically.
          </p>
          <div className="bg-paper border border-ink/10 rounded-lg p-4 my-3">
            <p className="font-mono text-sm text-center">
              Easy ≈ 41 clues · Medium ≈ 34 · Hard ≈ 28 · Expert ≈ 24 — fewer
              clues, harder logic
            </p>
          </div>
          <p className="mb-4">
            Every puzzle here is generated on the spot and verified to have
            exactly <strong>one</strong> solution — no guessing required, pure
            logic always works. Your progress, notes and timer survive a page
            refresh (until you close the tab), and 3 hints per puzzle reveal
            a cell when you are stuck.
          </p>
          <h2 className="font-display text-xl font-semibold mt-6 mb-3">
            Your privacy
          </h2>
          <p>
            The entire game — generation, solving and playing — runs locally
            in your browser. Nothing is{" "}
            <strong>sent to any server</strong> or stored anywhere.
          </p>
        </>
      }
      faqs={[
        {
          question: "How do you play Sudoku for beginners?",
          answer:
            "Fill the 9×9 grid so every row, every column and every 3×3 box has the digits 1–9 with no repeats. Start on Easy (about 41 clues): find a row, column or box that is nearly complete and deduce the missing digits. Tap a cell, then tap a number to place it.",
        },
        {
          question: "What is the difference between easy, medium, hard and expert?",
          answer:
            "Difficulty comes from how many clues you start with: Easy gives ~41 pre-filled digits, Medium ~34, Hard ~28 and Expert only ~24. Fewer clues mean longer deduction chains and advanced techniques like naked pairs and box-line reduction.",
        },
        {
          question: "Does every puzzle really have only one solution?",
          answer:
            "Yes. Each puzzle is generated by removing digits from a complete valid grid, and every removal is verified by a solver to keep the solution unique. If a removal would allow a second solution, the clue is put back.",
        },
        {
          question: "What are pencil notes and should I use them?",
          answer:
            "Notes (the ✏ button) let you mark small candidate digits in a cell. They are essential from Medium upward: track what could go where, and the puzzle practically solves itself as options get eliminated. Placing a digit automatically erases that candidate from related notes.",
        },
        {
          question: "Does the game save if I refresh the page?",
          answer:
            "Yes — your board, notes, timer and mistake count are kept in the browser's session storage and restored when you come back. Closing the tab starts a fresh puzzle (that is the point of session storage: nothing lingers).",
        },
        {
          question: "Can I play with the keyboard?",
          answer:
            "Yes: arrow keys (or WASD) move the selection, 1–9 place digits, N toggles notes, H uses a hint, U undoes and Backspace erases. On phones, simply tap cells and use the number pad.",
        },
      ]}
      relatedTools={[
        { name: "Snake Puzzle", href: "/tools/games/snake-puzzle" },
        { name: "Minesweeper", href: "/tools/games/minesweeper" },
        { name: "2048", href: "/tools/games/2048" },
        { name: "Memory Match", href: "/tools/games/memory-match" },
      ]}
    >
      <SudokuClient />
    </ToolLayout>
  );
}
